### PR TITLE
Upgrades Ruby to 2.3 and Rails to 4.2

### PR DESCRIPTION
**Pull request by corylown**
@seanaery @mikedaul this pull request updates the versions of Ruby and Rails for ddr-public. There are a few things you'll need to do in your VM environment to get this going:

1. In your VM's terminal install Ruby 2.3.1 with RVM and make sure that version is selected.
```
$ rvm install 2.3.1
$ cd /vagrant/ddr-public
$ rvm use 2.3.1
```
2. Install bundler:
`$ gem install bundler`

3. Install all the project's gems for this version of Ruby.
`$ bundle install`

4. To start the Rails server you will need run this command instead of just `rails s`.
`$ ./bin/rails s -b 0.0.0.0`

To get ready for Rails 5 and to reduce deprecation warnings in Rails 4.7.x you'll need to make a small change to following files (not in version control):

config/environments/production.rb
config/environments/test.rb
config/environments/development.rb

Change any occurrence of `config.serve_static_assets` to `config.serve_static_files`

Let me know if you run into any issues.

### CODE REVIEW

**Comment by seanaery** [comment]
@corylown This worked! Thanks for the thorough instructions.

**Comment by mikedaul** [comment]
Thanks Cory!

I followed the instructions and restarted the server, but got an error about solr not being found. So I tried restarting the VM and firing up jetty, and I get the following. Any ideas of something to try?

-Michael

+++

vagrant@precise64:/vagrant/ddr-public$ rake jetty:start
[DEPRECATION] the DC vocabulary will be moved to the rdf-vocab gem
for the RDF.rb 2.0 release. Use as RDF::Vocab::DC, or include RDF::Vocab in the RDF module.
Called from /home/vagrant/.rvm/gems/ruby-2.3.1/bundler/gems/ddr-models-e0ed623a3722/lib/ddr/datastreams/descriptive_metadata_datastream.rb:6
D, [2017-01-10T16:32:49.734017 #1940] DEBUG -- : Starting jetty with these values:
D, [2017-01-10T16:32:49.734459 #1940] DEBUG -- : jetty_home: /vagrant/ddr-public/jetty
D, [2017-01-10T16:32:49.734930 #1940] DEBUG -- : jetty_command: java -Djetty.port=8983 -Dsolr.solr.home=/vagrant/ddr-public/jetty/solr -Xmx256m -XX:MaxPermSize=128m -jar start.jar
rake aborted!
Errno::ENOENT: No such file or directory @ dir_chdir - /vagrant/ddr-public/jetty
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/jettywrapper-1.8.3/lib/jettywrapper.rb:362:in `chdir'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/jettywrapper-1.8.3/lib/jettywrapper.rb:362:in `block in start'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7/lib/active_support/benchmarkable.rb:41:in `block in benchmark'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/activesupport-4.2.7/lib/active_support/benchmarkable.rb:41:in `benchmark'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/jettywrapper-1.8.3/lib/jettywrapper.rb:361:in `start'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/jettywrapper-1.8.3/lib/jettywrapper.rb:234:in `start'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/jettywrapper-1.8.3/lib/tasks/jettywrapper.rake:30:in `block (2 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/vagrant/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => jetty:start
(See full trace by running task with --trace)

**Comment by corylown** [comment]
@mikedaul Try starting jetty from within the dul-hydra directory instead of ddr-public and see if that fixes it.

**Comment by mikedaul** [comment]
That did the trick – thanks!

Should we still be starting DDR-AUX as well?

**Comment by corylown** [comment]
@mikedaul yes -- everything else should be the same

**Pull request merged**
